spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingsystem
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
payment:
  success:
    probability: 0.8
server:
  port: 8080